assistant:
  provider: anthropic
  config:
    temperature: 0.7
    max_tokens: 1024
    top_p: 1.0
audio:
  config:
    channels: 1
    chunk_size: 1024
    sample_rate: 16000
    input_device: "default"
    output_device: "default"
  provider: pyaudio
clipboard:
  config: {}
  provider: qt
speech:
  provider: whisper
  config:
    whisper:
      model: "base"
    deepgram:
      model: "nova-2"
      language: "en"
      smart_format: true
      encoding: "linear16"
    f5tts:
      model: "F5-TTS"
      reference_audio_dir: "reference_audio"
ui:
  theme:
    mode: dark
    colors:
      background: "#000000"
      text: "#39FF14"
      accent: "#39FF14"
  window_size:
    - 800
    - 600
llm:
  providers:
    anthropic:
      default_model: "claude-3-sonnet"
      models:
        - "claude-3-opus"
        - "claude-3-sonnet"
        - "claude-3-haiku"
    openai:
      default_model: "gpt-4"
      models:
        - "gpt-4"
        - "gpt-3.5-turbo"
