assistant:
  provider: anthropic
  config:
    temperature: 0.7
    max_tokens: 1024
    top_p: 1.0
audio:
  config:
    channels: 1
    chunk_size: 1024
    sample_rate: 16000
    input_device: "default"
    output_device: "default"
  provider: pyaudio
clipboard:
  config: {}
  provider: qt
speech:
  provider: whisper
  config:
    whisper:
      model: "base"
    deepgram:
      model: "nova-2"
      language: "en"
      smart_format: true
      encoding: "linear16"
    f5tts:
      model: "F5-TTS"
      reference_audio_dir: "reference_audio" # Default directory for reference audio files
ui:
  theme:
    mode: dark
    colors:
      background: "#000000"
      text: "#39FF14"
      accent: "#39FF14"
  window_size:
    - 800
    - 600
# TODO: Configuration Status
# - Basic config structure in place
# - Need to add:
#   1. TTS-specific settings (model paths, voice profiles)
#   2. Audio processing settings (normalization, resampling)
#   3. Default voice reference settings
#   4. Error handling preferences
# - Consider:
#   1. Separate config for each TTS provider
#   2. Voice profile management
#   3. Audio quality settings
#   4. Resource paths configuration
